refactor: merge mkgifv into mkgif, support --fps parameter and unify naming convention

diff --git a/cli/mkgif b/cli/mkgif
--- a/cli/mkgif
+++ b/cli/mkgif
@@ -3,22 +3,44 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-# Description: Gif Maker (12fps, 480p, q100, supports local files and YouTube videos)
-# Usage: mkgif [input_file_or_url] [from(hh:mm:ss or sec)] [during(sec)]
+# Description: Gif Maker (Supports --fps [value] parameter, 480p, q100, local files and YouTube videos)
+# Usage: mkgif [--fps 12] [input_file_or_url] [from(hh:mm:ss or sec)] [during(sec)]
 # Example: mkgif 'input.mp4' 01:02:08 11.0
-#          mkgif JoSY6AWKqHs 00:01:59 2
+#          mkgif JoSY6AWKqHs 00:01:59 2 --fps 24
 
 ### Args
+FPS=12
+TEMP_ARGS=()
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    --fps)
+      if [[ $# -lt 2 ]]; then
+        echo "Error: --fps requires a value" >&2
+        exit 1
+      fi
+      FPS="$2"
+      shift 2
+      ;;
+    *)
+      TEMP_ARGS+=("$1")
+      shift 1
+      ;;
+  esac
+done
+
+# Restore positional parameters
+set -- "${TEMP_ARGS[@]}"
+
 INPUT_FILE=${1:-}
 START=${2:-}
 DURATION=${3:-}
 
 # Check arguments
 if [[ -z "$DURATION" ]]; then
-  printf "\033[1mmkgif\033[0m: Gif Maker (12fps, 480p, q100, supports local files and YouTube videos)\n" >&2
-  printf "Usage: \033[1mmkgif\033[0m [input_file_or_url] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
+  printf "\033[1mmkgif\033[0m: Gif Maker (Supports --fps [value] parameter, 480p, q100, local files and YouTube videos)\n" >&2
+  printf "Usage: \033[1mmkgif\033[0m [--fps 12] [input_file_or_url] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
   printf "       \033[1mmkgif\033[0m 'input.mp4' 01:02:08 11.0\n" >&2
-  printf "       \033[1mmkgif\033[0m JoSY6AWKqHs 00:01:59 2\n" >&2
+  printf "       \033[1mmkgif\033[0m JoSY6AWKqHs 00:01:59 2 --fps 24\n" >&2
   exit 1
 fi
 
@@ -55,12 +77,10 @@ fi
 
 ### quality
 QUALITY=85
-### fps
-FPS=12
 ### width
 WIDTH=480
 ### Output file
-OUTPUT_FILE="$(date +"%Y%m%d%H%M%S").gif"
+OUTPUT_FILE="$(date +"%Y%m%d%H%M%S")_fps${FPS}.gif"
 
 ffmpeg -y -hide_banner \
   -loglevel error \
